--CREATE DATABASE QUAN LY NGAN HANG
GO 
CREATE DATABASE QLNH
--DROP DATABASE QLNH
--DROP TABLE
GO
USE QLNH

-------------------TẠO BẢNG CHO CƠ SỞ DỮ LIỆU-------------------
GO
----Bang nhan vien (Lê Nguyễn Phú Lợi)
CREATE TABLE NHANVIEN(MANV CHAR(10) NOT NULL,
						TENNV NVARCHAR(30) NOT NULL,
						GIOITINH NVARCHAR(5),
						NGAYSINH DATE,
						CHUC NVARCHAR(50),
						LUONG FLOAT,
						DIACHI NVARCHAR(50),
						SDT INT,
						MAPB INT,
						MACN CHAR(10))
GO
----Bang phong ban
CREATE TABLE PHONGBAN(MAPB INT NOT NULL,
						TENPB NVARCHAR(15) NOT NULL)
GO
----Bang chi nhanh
CREATE TABLE CHINHANH(MACN CHAR(10) NOT NULL,
						TENCN NVARCHAR(50) NOT NULL,
						DIACHICN NVARCHAR(50) NOT NULL,
						SDTCN INT)
GO 
----Bang noi quy
CREATE TABLE NOIQUY(MANQ CHAR(10) NOT NULL,
					TIEUDE NVARCHAR(100) NOT NULL,
					MOTA NVARCHAR(100),
					NGAYBH DATE,
					LOAIAPDUNG NVARCHAR(225))
GO
----Bang vi pham
CREATE TABLE VIPHAM(MAVP CHAR(10) NOT NULL,
					MANQ CHAR(10),
					MANV CHAR(10),
					NGAYVP DATE,
					MOTAVP NVARCHAR(100),
					HINHTHUCXL NVARCHAR(100),
					TRANGTHAIXL NVARCHAR(100))

GO

--BANG LOGIN
CREATE TABLE DANGNHAP(MADN CHAR(20) NOT NULL,
					PASS CHAR(50),
					QUYEN NVARCHAR(50),
					MANV CHAR(10))


---BẢNG KHÁCH HÀNG (LÊ NGUYÊN VĨ)
--CCCD VÀ SDT NÊN SỬ DỤNG VARCHAR VÌ NÓ CÓ THỂ CHỨA KÝ TỰ BẮT ĐẦU BẰNG SỐ 0 CÒN KIỂU INT THÌ SẼ BỎ MẤT SỐ 0 Ở ĐẦU (VARCHAR:0384629483, INT:384629483)
GO
CREATE TABLE KHACHHANG(MAKH CHAR(10) NOT NULL,
						TENKH NVARCHAR(70),
						GIOITINH NVARCHAR(10),
						CCCD VARCHAR(12),
						SDT VARCHAR(10),
						EMAIL NVARCHAR(100),
						DIACHI NVARCHAR(100),
						QUOCTICH NVARCHAR(20),
						DOITUONG NVARCHAR(20),
						NGAYTAO DATETIME)

---BẢNG LOẠI TÀI KHOẢN
GO
CREATE TABLE LOAITK(MALOAITK VARCHAR(10) NOT NULL,
							CHITIET NVARCHAR(30),
							NGAYTAO DATETIME,
							NGAYCAPNHAT DATETIME,
							TRANGTHAI NVARCHAR(20))

---BẢNG LOẠI GIAO DỊCH
GO
CREATE TABLE LOAIGD(MALOAIGD VARCHAR(10) NOT NULL,
							TENLOAIGD NVARCHAR(30),
							NGAYLAP DATETIME,
							NGAYCAPNHAT DATETIME,
							TRANGTHAI NVARCHAR(20))

---BẢNG LOẠI HỢP ĐỒNG
GO
CREATE TABLE LOAIHD(MALOAIHD VARCHAR(10) NOT NULL,
							TENLOAIHD NVARCHAR(30),
							NGAYLAP DATETIME,
							NGAYCAPNHAT DATETIME,
							TRANGTHAI NVARCHAR(20))

---BẢNG LOẠI HỖ TRỢ
GO
CREATE TABLE LOAIHT(MALOAIHT VARCHAR(10) NOT NULL,
							TENLOAIHT NVARCHAR(30),
							NGAYLAP DATETIME,
							NGAYCAPNHAT DATETIME,
							TRANGTHAI NVARCHAR(20))


---BẢNG TÀI KHOẢN 
GO
CREATE TABLE TAIKHOAN(MATK CHAR(10) NOT NULL,
							MAKH CHAR(10),
							SOTAIKHOAN VARCHAR(10),
							MALOAITK VARCHAR(10),
							SODU DECIMAL,
							MANGOAITE VARCHAR(10),
							NGAYMOTK DATETIME,
							TRANGTHAI NVARCHAR(20))

---BẢNG GIAO DỊCH 
GO
CREATE TABLE GIAODICH(MAGD CHAR(10) NOT NULL,
						MAKH CHAR(10) NOT NULL,
						MATK CHAR(10) NOT NULL,
						MALOAIGD VARCHAR(10),
						SOTIEN DECIMAL,
						THOIGIANGD DATETIME,
						MOTA NVARCHAR(100),
						TRANGTHAI NVARCHAR(20))
			
---BẢNG HỖ TRỢ
GO
CREATE TABLE HOTRO(MAHTRO CHAR(10) NOT NULL,
					MAKH CHAR(10) NOT NULL,
					MANV CHAR(10) NOT NULL,
					MALOAIHT VARCHAR(10),
					NOIDUNG NVARCHAR(200),
					NGAYHTRO DATETIME)

---BẢNG HỢP ĐỒNG
GO
CREATE TABLE HOPDONG(MAHD INT IDENTITY(1,1) PRIMARY KEY,
						SOHOPDONG NVARCHAR(10) NOT NULL,
						MALOAIHD VARCHAR(10) NOT NULL,
						NGAYKY DATETIME,
						NGAYHETHAN DATETIME,
						GIATRI DECIMAL,
						GHICHU NVARCHAR(500),
						TRANGTHAI NVARCHAR(20),
						MANV CHAR(10) NOT NULL,
						MAKH CHAR(10) NOT NULL)

GO
---BANG CHUYEN KHOAN (Nguyễn Khánh Đăng)
CREATE TABLE CHUYENKHOAN(MACK CHAR(10) NOT NULL,
							MAKH CHAR(10) NOT NULL,
							MATK CHAR(10) NOT NULL,
							NGAYCK DATETIME, 
							SOTIEN DECIMAL, 
							MATKGUI CHAR(10), 
							MATKNHAN CHAR(10), 
							NOIDUNG NVARCHAR(250))
GO
---BANG KHOAN VAY
CREATE TABLE KHOANVAY(MAVAY CHAR(10) NOT NULL,
						MAKH CHAR(10), 
						MATK CHAR(10),
						SOTIENVAY DECIMAL,
						NGAYVAY DATETIME, 
						THOIHAN DATETIME,
						TRANGTHAI NVARCHAR(50), 	
						MALAISUAT CHAR(10))
GO
---BANG LAI SUAT
CREATE TABLE LAISUAT(MALAISUAT CHAR(10) NOT NULL, 
						TENLOAIVAY NVARCHAR(250), 
						LAISUAT DECIMAL,
						KIEULAI NVARCHAR(50))
GO
---BANG TRA NO
CREATE TABLE TRANO(MATRANO CHAR(10) NOT NULL,
						MAVAY CHAR(10),
						SOTIENO DECIMAL,
						SOTIENTRA DECIMAL,
						NGAYTRA DATETIME)
GO
--BANG KHUYEN MAI
CREATE TABLE KHUYENMAI(MAKM CHAR(10) NOT NULL, 
						TENKM NVARCHAR(250), 
						MOTA NVARCHAR(250), 
						NGAYBD DATETIME, 
						NGAYKT DATETIME, 
						DKAPDUNG NVARCHAR(250))
GO
--BANG AP DUNG KHUYEN MAI
CREATE TABLE APDUNGKHUYENMAI(MAKM CHAR(10) NOT NULL, 
						MAKH CHAR(10) NOT NULL, 
						MATK CHAR(10), 
						NGAYAPDUNG DATETIME)

--BANG NGOAI TE
GO
CREATE TABLE NGOAITE(MANGOAITE VARCHAR(10) NOT NULL,
						TENNGOAITE NVARCHAR(50),
						KYHIEU NVARCHAR(10),
						QUOCGIA NVARCHAR(20),
						TRANGTHAI NVARCHAR(20))

--BANG BIEN LAI
GO
CREATE TABLE BIENLAI(MABL CHAR(10) NOT NULL,
						MAGD CHAR(10),
						MAKH CHAR(10),
						MATK CHAR(10),
						MANV CHAR(10),
						SOTIEN DECIMAL,
						MANGOAITE CHAR(10),
						LOAIBL NVARCHAR(30),
						MOTA NVARCHAR(250),
						TRANGTHAI NVARCHAR(20))	



-------------------RÀNG BUỘC KHÓA CHÍNH-------------------
GO
--KHOA CHINH NHANVIEN
ALTER TABLE NHANVIEN
ADD CONSTRAINT PK_NV PRIMARY KEY(MANV)
GO
--KHOA CHINH PHONG BAN
ALTER TABLE PHONGBAN
ADD CONSTRAINT PK_PB PRIMARY KEY(MAPB)
GO
--KHOA CHINH CHI NHANH
ALTER TABLE CHINHANH
ADD CONSTRAINT PK_CN PRIMARY KEY(MACN)
GO
--KHOA CHINH NOI QUY
ALTER TABLE NOIQUY
ADD CONSTRAINT PK_NQ PRIMARY KEY(MANQ)
GO
--KHOA CHINH VI PHAM
ALTER TABLE VIPHAM
ADD CONSTRAINT PK_VP PRIMARY KEY(MAVP)
GO

--KHOA CHINH CHO LOGIN
GO
ALTER TABLE DANGNHAP
ADD CONSTRAINT PK_LG PRIMARY KEY(MADN)


------LÊ NGUYÊN VĨ------
---KHÓA CHÍNH CHO BẢNG KHÁCH HÀNG---
GO
ALTER TABLE KHACHHANG
ADD CONSTRAINT PK_KH PRIMARY KEY(MAKH)

---KHÓA CHÍNH CHO BẢNG LOẠI KHÁCH HÀNG---
GO
ALTER TABLE LOAITK
ADD CONSTRAINT PK_LTK PRIMARY KEY(MALOAITK)


--KHÓA CHÍNH CHO BẢNG TÀI KHOẢN---
GO
ALTER TABLE TAIKHOAN
ADD CONSTRAINT PK_TK PRIMARY KEY(MATK)

--KHÓA CHÍNH CHO BẢNG GIAO DỊCH---
GO
ALTER TABLE GIAODICH
ADD CONSTRAINT PK_GD PRIMARY KEY(MAGD, MAKH, MATK)

--KHÓA CHÍNH CHO BẢNG HỖ TRỢ---
GO
ALTER TABLE HOTRO
ADD CONSTRAINT PK_HT PRIMARY KEY(MAHTRO, MAKH, MANV)

--KHÓA CHÍNH CHO BẢNG LOẠI GIAO DỊCH---
GO
ALTER TABLE LOAIGD
ADD CONSTRAINT PK_LGD PRIMARY KEY(MALOAIGD)

--KHÓA CHÍNH CHO BẢNG LOẠI HỢP ĐỒNG---
GO
ALTER TABLE LOAIHD
ADD CONSTRAINT PK_LHD PRIMARY KEY(MALOAIHD)

--KHÓA CHÍNH CHO BẢNG LOẠI HỖ TRỢ---
GO
ALTER TABLE LOAIHT
ADD CONSTRAINT PK_LHt PRIMARY KEY(MALOAIHT)




----NGUYỄN KHÁNH ĐĂNG---
--KHOA CHINH CHO BANG CHUYEN KHOAN
GO
ALTER TABLE CHUYENKHOAN
ADD CONSTRAINT PK_CK PRIMARY KEY(MACK, MAKH, MATK)

--KHOA CHINH CHO BANG KHOAN VAY
GO
ALTER TABLE KHOANVAY
ADD CONSTRAINT PK_KV PRIMARY KEY(MAVAY)

--KHOA CHINH CHO BANG LAI SUAT
GO
ALTER TABLE LAISUAT
ADD CONSTRAINT PK_LS PRIMARY KEY(MALAISUAT)

--KHOA CHINH CHO BANG TRA NO
GO
ALTER TABLE TRANO
ADD CONSTRAINT PK_TN PRIMARY KEY(MATRANO)

--KHOA CHINH CHO BANG KHUYEN MAI
GO
ALTER TABLE KHUYENMAI
ADD CONSTRAINT PK_KM PRIMARY KEY(MAKM)

--KHOA CHINH CHO BANG AP DUNG KHUYEN MAI
GO
ALTER TABLE APDUNGKHUYENMAI
ADD CONSTRAINT PK_ADKM PRIMARY KEY(MAKM,MAKH)

--KHOA CHINH CHO NGOAI
GO
ALTER TABLE NGOAITE
ADD CONSTRAINT PK_LTT PRIMARY KEY(MANGOAITE)

--KHOA CHINH CHO BIEN LAI
GO
ALTER TABLE BIENLAI
ADD CONSTRAINT PK_BL PRIMARY KEY(MABL)




-------------------RÀNG BUỘC KHÓA NGOẠI-------------------
---NHAN VIEN VOI PHONG BAN
GO
ALTER TABLE NHANVIEN
ADD CONSTRAINT FK_NV_PB FOREIGN KEY(MAPB)
REFERENCES PHONGBAN(MAPB)

---NHAN VIEN VOI CHI NHANH
GO
ALTER TABLE NHANVIEN
ADD CONSTRAINT FK_NV_CN FOREIGN KEY(MACN)
REFERENCES CHINHANH(MACN)

GO
-- LOGIN VỚI NHÂNVIEN
ALTER TABLE DANGNHAP
ADD CONSTRAINT FK_DN_NV FOREIGN KEY (MANV)
REFERENCES NHANVIEN(MANV)
GO

---BIEN LAI VOI NHAN VIEN
GO
ALTER TABLE BIENLAI
ADD CONSTRAINT FK_BL_NV FOREIGN KEY(MANV)
REFERENCES NHANVIEN(MANV)

---BIEN LAI VOI KHACH HANG
GO
ALTER TABLE BIENLAI
ADD CONSTRAINT FK_BL_KH FOREIGN KEY(MAKH)
REFERENCES KHACHHANG(MAKH)

---TAI KHOAN VOI KHACH HANG
GO
ALTER TABLE TAIKHOAN
ADD CONSTRAINT FK_TK_KH FOREIGN KEY(MAKH)
REFERENCES KHACHHANG(MAKH)

---TAI KHOAN VOI LOAI KHACH HANG
GO
ALTER TABLE TAIKHOAN
ADD CONSTRAINT FK_TK_LKH FOREIGN KEY(MALOAITK)
REFERENCES LOAITK(MALOAITK)


---TAI KHOAN VOI LOAI TIEN
GO
ALTER TABLE TAIKHOAN
ADD CONSTRAINT FK_TK_NT FOREIGN KEY(MANGOAITE)
REFERENCES NGOAITE(MANGOAITE)

---CHUYEN KHOAN VOI KHACH HANG
GO
ALTER TABLE CHUYENKHOAN
ADD CONSTRAINT FK_CKG_KH FOREIGN KEY(MAKH)
REFERENCES KHACHHANG(MAKH)

---CHUYEN KHOAN VOI TAI KHOAN
GO
ALTER TABLE CHUYENKHOAN
ADD CONSTRAINT FK_CKG_TK FOREIGN KEY(MATK)
REFERENCES TAIKHOAN(MATK)

---KHOAN VAY VOI KHACH HANG
GO
ALTER TABLE KHOANVAY
ADD CONSTRAINT FK_KV_KH FOREIGN KEY(MAKH)
REFERENCES KHACHHANG(MAKH)

---KHOAN VAY VOI TAI KHOAN
GO
ALTER TABLE KHOANVAY
ADD CONSTRAINT FK_KV_TK FOREIGN KEY(MATK)
REFERENCES TAIKHOAN(MATK)

---KHOAN VAY VOI LAI SUAT
GO
ALTER TABLE KHOANVAY
ADD CONSTRAINT FK_KV_LS FOREIGN KEY(MALAISUAT)
REFERENCES LAISUAT(MALAISUAT)

---TRA NO VOI KHOAN VAY
GO
ALTER TABLE TRANO
ADD CONSTRAINT FK_LSTN_KV FOREIGN KEY(MAVAY)
REFERENCES KHOANVAY(MAVAY)

---AP DUNG KHUYEN MAI VOI KHUYEN MAI
GO
ALTER TABLE APDUNGKHUYENMAI
ADD CONSTRAINT FK_ADKM_KM FOREIGN KEY(MAKM)
REFERENCES KHUYENMAI(MAKM)

---AP DUNG KHUYEN MAI VOI KHACH HANG
GO
ALTER TABLE APDUNGKHUYENMAI
ADD CONSTRAINT FK_ADKM_KH FOREIGN KEY(MAKH)
REFERENCES KHACHHANG(MAKH)

---AP DUNG KHUYEN MAI VOI TAI KHOAN
GO
ALTER TABLE APDUNGKHUYENMAI
ADD CONSTRAINT FK_ADKM_TK FOREIGN KEY(MATK)
REFERENCES TAIKHOAN(MATK)

---VI PHAM VOI NOI QUY
GO
ALTER TABLE VIPHAM
ADD CONSTRAINT FK_VP_NQ FOREIGN KEY(MANQ)
REFERENCES NOIQUY(MANQ)

---VI PHAM VOI NHAN VIEN
GO
ALTER TABLE VIPHAM
ADD CONSTRAINT FK_VP_NV FOREIGN KEY(MANV)
REFERENCES NHANVIEN(MANV)


---GIAO DICH VOI TAI KHOAN
GO
ALTER TABLE GIAODICH
ADD CONSTRAINT FK_GD_TK FOREIGN KEY(MATK)
REFERENCES TAIKHOAN(MATK)

---GIAO DICH VOI KHACH HANG
GO
ALTER TABLE GIAODICH
ADD CONSTRAINT FK_GD_KH FOREIGN KEY(MAKH)
REFERENCES KHACHHANG(MAKH)

---GIAO DICH VOI LOAI GIAO DICH
GO
ALTER TABLE GIAODICH
ADD CONSTRAINT FK_GD_LGD FOREIGN KEY(MALOAIGD)
REFERENCES LOAIGD(MALOAIGD)

---HO TRO VOI KHACH HANG
GO
ALTER TABLE HOTRO
ADD CONSTRAINT FK_HT_KH FOREIGN KEY(MAKH)
REFERENCES KHACHHANG(MAKH)

---HO TRO VOI NHANVIEN
GO
ALTER TABLE HOTRO
ADD CONSTRAINT FK_HT_NV FOREIGN KEY(MANV)
REFERENCES NHANVIEN(MANV)

---HO TRO VOI LOAI HO TRO
GO
ALTER TABLE HOTRO
ADD CONSTRAINT FK_HT_LHT FOREIGN KEY(MALOAIHT)
REFERENCES LOAIHT(MALOAIHT)

---HOP DONG VOI KHACH HANG
GO
ALTER TABLE HOPDONG
ADD CONSTRAINT FK_HD_KH FOREIGN KEY(MAKH)
REFERENCES KHACHHANG(MAKH)

---HOP DONG VOI NHANVIEN
GO
ALTER TABLE HOPDONG
ADD CONSTRAINT FK_HD_NV FOREIGN KEY(MANV)
REFERENCES NHANVIEN(MANV)

---HOP DONG VOI LOAI HOP DONG
GO
ALTER TABLE HOPDONG
ADD CONSTRAINT FK_HD_LHD FOREIGN KEY(MALOAIHD)
REFERENCES LOAIHD(MALOAIHD)

-------------------RÀNG BUỘC DUY NHẤT-------------------
-----LÊ NGUYỄN PHÚ LỢI-----
---TÊN LÃI SUẤT LÀ DUY NHẤT
GO
ALTER TABLE LAISUAT
ADD CONSTRAINT TEN_LS UNIQUE(TENLOAIVAY)

-----NGUYỄN KHÁNH ĐĂNG-----
---SDT NHAN VIEN LA DUY NHAT---
GO
ALTER TABLE NHANVIEN
ADD CONSTRAINT SDT_NV UNIQUE(SDT)
---TEN PHONG BAN LA DUY NHAT---
GO 
ALTER TABLE PHONGBAN
ADD CONSTRAINT TENPB_PB UNIQUE(TENPB)
---TEN CHI NHANH LA DUY NHAT---
GO
ALTER TABLE CHINHANH
ADD CONSTRAINT TENCN_CN UNIQUE(TENCN)
---SDT CHI NHANH LA DUY NHAT---
GO
ALTER TABLE CHINHANH
ADD CONSTRAINT SDTCN_CN UNIQUE(SDTCN)
---TIEUDE LA DUY NHAT---
GO	
ALTER TABLE NOIQUY
ADD CONSTRAINT TIEUDE_NQ UNIQUE(TIEUDE)

------LÊ NGUYÊN VĨ------
---CCCD KHÁCH HÀNG LÀ DUY NHẤT---
GO
ALTER TABLE KHACHHANG 
ADD CONSTRAINT CCCD_KH UNIQUE(CCCD)

---SDT KHÁCH HÀNG LÀ DUY NHẤT---
GO
ALTER TABLE KHACHHANG
ADD CONSTRAINT SDT_KH UNIQUE(SDT)

---EMAIL KHÁCH HÀNG LÀ DUY NHẤT---
GO
ALTER TABLE KHACHHANG
ADD CONSTRAINT EMAIL_KH UNIQUE(EMAIL)

---SỐ TÀI KHOẢN LÀ DUY NHẤT---
GO
ALTER TABLE TAIKHOAN
ADD CONSTRAINT SOTAIKHOAN_TK UNIQUE(SOTAIKHOAN)


GO
ALTER TABLE DANGNHAP ADD CONSTRAINT UQ_LG_MANV UNIQUE (MANV)



-------------------RÀNG BUỘC MIỀN GIÁ TRỊ-------------------

-----NGUYỄN KHÁNH ĐĂNG-----
---GIOI TINH CHO NHAN VIEN---
GO 
ALTER TABLE NHANVIEN
ADD CONSTRAINT CK_GTNV CHECK(GIOITINH = N'NAM' OR GIOITINH = N'NỮ')
---TRANG THAI XU LY VI PHAM NHAN VIEN---
GO
ALTER TABLE VIPHAM
ADD CONSTRAINT CK_TTXL CHECK(TRANGTHAIXL = N'ĐÃ XỬ LÝ' OR TRANGTHAIXL = N'CHƯA XỬ LÝ')

------LÊ NGUYÊN VĨ------
---GIỚI TÍNH NAM/NỮ CHO KHÁCH HÀNG---
GO
ALTER TABLE KHACHHANG
ADD CONSTRAINT CK_GTKH CHECK(GIOITINH = N'NAM' OR GIOITINH = N'NỮ')

---TRẠNG THÁI CHO BIÊN LAI---
GO
ALTER TABLE BIENLAI
ADD CONSTRAINT CK_TTBL CHECK(TRANGTHAI = N'ĐÃ IN' OR TRANGTHAI = N'CHƯA IN')

---NGAY KET THUC CHO KHUYEN MAI
GO
ALTER TABLE KHUYENMAI
ADD CONSTRAINT CK_NKT
CHECK (NGAYKT >= NGAYBD);

-------------------RÀNG BUỘC MẶC ĐỊNH-------------------

------LÊ NGUYÊN VĨ------
---MẶC ĐỊNH SỐ DƯ CHO TAIKHOAN---
GO
ALTER TABLE TAIKHOAN
ADD CONSTRAINT DF_SODU DEFAULT 0 FOR SODU
